### ISSUE TITLE
Opening other pages of the Kandex hangs program.

### ISSUE THREAD

**Issue by v905844** [RyuuKitsune/ElectronicObserver#15]
Every single time I try to open anything execept the first page of tabs of the Kandex, it will inexplicably hang for no good reason, forcing me to terminate the program.

To be sure that its not a browser issue i had used IE as well as other IE-based viewers like KCV and also tried KC3 and Firefox to see if it also affects. all of them had failed to reproduce the result. 

I have not managed to acquire any logs that may help pinpoint the problem though.

**Comment by RyuuKitsune** [comment]
You mean the in game library, correct? I'll take a look at this one after the 1.6.3 update, it's possible it's already fixed upstream. If not, though, I'll see about fixing it.

**Comment by RyuuKitsune** [comment]
Not reproducible in v1.6.3, which should be out soon enough. If it happens again for you after the patch is released, I can reopen the issue.
