### ISSUE TITLE
Misplaced Battle screen detail

### ISSUE THREAD

**Issue by ghost** [RyuuKitsune/ElectronicObserver#19]
As you can see. The Items are misplaced Lv. Yuudachi Kai Ni which should be the 98 that is shown below where the HP before is displayed. Hope this gets fixed :> 
![eo bug](https://cloud.githubusercontent.com/assets/14480510/11318486/65851c42-908f-11e5-85d3-9acd1abe01c5.jpg)

**Comment by RyuuKitsune** [comment]
Fixed in da379e1d84264505057c939e4744f32861b18f46, will be released with 2.0.0. Thanks for the report!
