### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by kevin01523** [RyuuKitsune/ElectronicObserver#9]
T74Eo latest release wont open or even load or any windows appear now tested on 2 computers

**Comment by silfumus** [comment]
Yup, System.Net.WebException.
I suppose it's related with recent changes in ryuukitsune.github.io

Edit: Fixed already, thanks.
Https://github.com/RyuuKitsune/ryuukitsune.github.io/commit/a1fa8a719ffb15c965de256d4ba64db619c81ee1

**Comment by kevin01523** [comment]
haha cant do event in t74 eo well im trying to build the translate branch now

**Comment by RyuuKitsune** [comment]
Yep, as silfumus said, it was an issue with changes I'm doing to the translator's online updates. It's fixed now, that was an embarrassing bug.

**Comment by kevin01523** [comment]
good to hear i cloned it and built it on my pc so i was able to use it a few hours ago
